-- Active: 1761117141890@@127.0.0.1@5434@postgres
-- BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS users (
    -- id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    id SERIAL NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    hash VARCHAR(255) NOT NULL
    -- created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- COMMIT;