// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetUserByLogin(ctx context.Context, login string) (GetUserByLoginRow, error)
}

var _ Querier = (*Queries)(nil)
