// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (login, hash)
VALUES ($1, $2)
RETURNING
    id,
    login,
    hash
`

type CreateUserParams struct {
	Login string `json:"login"`
	Hash  string `json:"hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Login, arg.Hash)
	var i User
	err := row.Scan(&i.ID, &i.Login, &i.Hash)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, hash FROM users WHERE login = $1 LIMIT 1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(&i.ID, &i.Login, &i.Hash)
	return i, err
}
